name: .NET Formatting

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  check-formatting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x
      - name: Install CSharpier
        run: dotnet tool install csharpier -g
      - name: Add .dotnet/tools to PATH
        run: echo "::add-path::/root/.dotnet/tools"
      - name: Restore tools
        run: dotnet tool restore
      - name: Check formatting with CSharpier
        run: dotnet csharpier --check .
